export interface Question {
  id: number;
  type: 'assertion-reason' | 'match-following' | 'analyse-situation';
  text: string;
  options: string[];
  correctIndex: number;
}

type QBank = Record<string, Question[]>;

const questionBank: QBank = {
  'Artificial Intelligence': [
    { id:1, type:'assertion-reason', text:'Assertion: Neural networks can approximate any continuous function.\nReason: The Universal Approximation Theorem guarantees convergence in finite training steps.', options:['Both A and R are true, R is correct explanation of A','Both true, R is NOT correct explanation of A','A is true, R is false','A is false, R is true'], correctIndex:2 },
    { id:2, type:'analyse-situation', text:'A model achieves 99% accuracy on training data but 52% on test data. You notice the model has 500 layers for a dataset of 1000 samples. What is the BEST course of action?', options:['Increase training epochs','Reduce model complexity and apply regularization','Collect exactly 500 more samples','Increase the learning rate'], correctIndex:1 },
    { id:3, type:'match-following', text:'Match: (P) Gradient Descent (Q) Backpropagation (R) Dropout (S) Batch Normalization\nWith: (1) Regularization technique (2) Optimization algorithm (3) Chain rule application (4) Normalizing activations', options:['P-2, Q-3, R-1, S-4','P-3, Q-2, R-4, S-1','P-2, Q-1, R-3, S-4','P-1, Q-3, R-2, S-4'], correctIndex:0 },
    { id:4, type:'analyse-situation', text:'You\'re building a spam classifier. Your dataset has 95% non-spam and 5% spam. A model that always predicts "non-spam" gets 95% accuracy. What metric should you prioritize?', options:['Accuracy','F1-Score or Precision-Recall','Mean Squared Error','R-squared'], correctIndex:1 },
    { id:5, type:'assertion-reason', text:'Assertion: Convolutional Neural Networks work well for image recognition.\nReason: Convolution operations preserve spatial relationships between pixels.', options:['Both A and R true, R explains A','Both true, R does NOT explain A','A true, R false','Both false'], correctIndex:0 },
    { id:6, type:'analyse-situation', text:'Your reinforcement learning agent keeps choosing the same action regardless of state. Training reward is flat. The most likely issue is:', options:['Learning rate too low','Exploration rate (epsilon) is effectively zero','The environment is deterministic','The discount factor is too high'], correctIndex:1 },
    { id:7, type:'match-following', text:'Match the loss function to its best use case:\n(P) Cross-Entropy (Q) MSE (R) Hinge Loss (S) Triplet Loss\nWith: (1) SVM (2) Classification (3) Regression (4) Similarity Learning', options:['P-2, Q-3, R-1, S-4','P-3, Q-2, R-4, S-1','P-1, Q-4, R-2, S-3','P-4, Q-1, R-3, S-2'], correctIndex:0 },
    { id:8, type:'assertion-reason', text:'Assertion: Transfer learning reduces training time for new tasks.\nReason: Pre-trained models have already learned general features from large datasets.', options:['Both true, R explains A','Both true, R does NOT explain A','A true, R false','Both false'], correctIndex:0 },
    { id:9, type:'analyse-situation', text:'A GAN generates realistic images but every output looks nearly identical. This problem is called:', options:['Vanishing gradients','Mode collapse','Overfitting','Underfitting'], correctIndex:1 },
    { id:10, type:'analyse-situation', text:'You fine-tune a large language model on medical Q&A data. It performs well on medical questions but now fails at basic math. This is an example of:', options:['Overfitting','Catastrophic forgetting','Underfitting','Data leakage'], correctIndex:1 },
  ],
  'Electrical Engineering': [
    { id:1, type:'assertion-reason', text:'Assertion: A capacitor blocks DC current in steady state.\nReason: The impedance of a capacitor is inversely proportional to frequency.', options:['Both true, R explains A','Both true, R does NOT explain A','A true, R false','Both false'], correctIndex:0 },
    { id:2, type:'analyse-situation', text:'You measure 0V across a resistor in a series circuit that is powered on. The most likely cause is:', options:['The resistor has infinite resistance','The resistor has zero resistance (short circuit)','The power supply is faulty','The multimeter is broken'], correctIndex:1 },
    { id:3, type:'match-following', text:'Match: (P) BJT (Q) MOSFET (R) Op-Amp (S) Diode\nWith: (1) Voltage-controlled device (2) Current-controlled device (3) Virtual ground principle (4) PN junction', options:['P-2, Q-1, R-3, S-4','P-1, Q-2, R-4, S-3','P-4, Q-3, R-1, S-2','P-3, Q-4, R-2, S-1'], correctIndex:0 },
    { id:4, type:'analyse-situation', text:'An LED in your circuit doesn\'t light up. You check: supply is 5V, resistor is 10kΩ, LED forward voltage is 2V. What\'s wrong?', options:['LED is reversed','Resistor value too high, insufficient current','Supply voltage insufficient','Ground not connected'], correctIndex:1 },
    { id:5, type:'assertion-reason', text:'Assertion: Three-phase power is preferred for industrial motors.\nReason: Three-phase provides constant power delivery unlike single-phase pulsating power.', options:['Both true, R explains A','Both true, R does NOT explain A','A true, R false','Both false'], correctIndex:0 },
    { id:6, type:'analyse-situation', text:'In a common-emitter amplifier, increasing the collector resistance RC while keeping everything else constant will:', options:['Increase voltage gain and decrease bandwidth','Decrease both voltage gain and bandwidth','Have no effect on gain','Increase bandwidth only'], correctIndex:0 },
    { id:7, type:'match-following', text:'Match filter type with characteristic:\n(P) Low-pass (Q) High-pass (R) Band-pass (S) Notch\nWith: (1) Removes specific frequency (2) Passes low frequencies (3) Passes range of frequencies (4) Blocks low frequencies', options:['P-2, Q-4, R-3, S-1','P-4, Q-2, R-1, S-3','P-1, Q-3, R-4, S-2','P-3, Q-1, R-2, S-4'], correctIndex:0 },
    { id:8, type:'assertion-reason', text:'Assertion: A transformer cannot work with DC input.\nReason: Transformers rely on changing magnetic flux to induce voltage.', options:['Both true, R explains A','Both true, R does NOT explain A','A true, R false','Both false'], correctIndex:0 },
    { id:9, type:'analyse-situation', text:'Your oscilloscope shows a 5V peak-to-peak sine wave with DC offset of 2.5V. The signal never goes negative. What is the minimum voltage?', options:['0V','-2.5V','2.5V','5V'], correctIndex:0 },
    { id:10, type:'analyse-situation', text:'Two resistors rated 100Ω each are connected in parallel. A student claims total resistance is 200Ω. The actual value is:', options:['200Ω','100Ω','50Ω','25Ω'], correctIndex:2 },
  ],
  'Physics': [
    { id:1, type:'assertion-reason', text:'Assertion: An astronaut in orbit feels weightless.\nReason: There is no gravitational force in space.', options:['Both true, R explains A','Both true, R does NOT explain A','A true, R false','Both false'], correctIndex:2 },
    { id:2, type:'analyse-situation', text:'A ball is thrown upward. At its highest point, the acceleration is:', options:['Zero (velocity is zero)','9.8 m/s² downward','9.8 m/s² upward','Undefined'], correctIndex:1 },
    { id:3, type:'match-following', text:'Match: (P) Entropy (Q) Enthalpy (R) Gibbs Free Energy (S) Internal Energy\nWith: (1) Total heat content (2) Spontaneity criterion (3) Disorder measure (4) First law quantity', options:['P-3, Q-1, R-2, S-4','P-1, Q-3, R-4, S-2','P-2, Q-4, R-1, S-3','P-4, Q-2, R-3, S-1'], correctIndex:0 },
    { id:4, type:'analyse-situation', text:'Two identical blocks, one on Earth and one on the Moon, are pushed with the same force. Which accelerates faster?', options:['Earth block (stronger gravity aids motion)','Moon block (same mass, same force, same acceleration)','Moon block (less friction due to less normal force)','Neither, they accelerate equally'], correctIndex:2 },
    { id:5, type:'assertion-reason', text:'Assertion: Light bends when passing from air to water.\nReason: Light travels slower in water than in air.', options:['Both true, R explains A','Both true, R does NOT explain A','A true, R false','Both false'], correctIndex:0 },
    { id:6, type:'analyse-situation', text:'Doubling the distance between two charges reduces the electrostatic force to:', options:['Half','One-quarter','One-eighth','Stays the same'], correctIndex:1 },
    { id:7, type:'match-following', text:'Match: (P) Doppler Effect (Q) Photoelectric Effect (R) Compton Scattering (S) Pair Production\nWith: (1) Particle nature of light (2) Frequency shift (3) Photon-electron collision (4) Energy to mass', options:['P-2, Q-1, R-3, S-4','P-1, Q-2, R-4, S-3','P-3, Q-4, R-2, S-1','P-4, Q-3, R-1, S-2'], correctIndex:0 },
    { id:8, type:'assertion-reason', text:'Assertion: Ice floats on water.\nReason: Water expands when it freezes, making ice less dense than liquid water.', options:['Both true, R explains A','Both true, R does NOT explain A','A true, R false','Both false'], correctIndex:0 },
    { id:9, type:'analyse-situation', text:'A car goes around a circular track at constant speed. Its acceleration is:', options:['Zero (constant speed)','Directed toward center of circle','Directed tangentially','Directed outward from center'], correctIndex:1 },
    { id:10, type:'analyse-situation', text:'In a perfectly inelastic collision, what is conserved?', options:['Both momentum and kinetic energy','Only kinetic energy','Only momentum','Neither'], correctIndex:2 },
  ],
  'Mathematics': [
    { id:1, type:'assertion-reason', text:'Assertion: The derivative of eˣ is eˣ.\nReason: eˣ is the only function that is its own derivative.', options:['Both true, R explains A','Both true, R does NOT explain A','A true, R false','Both false'], correctIndex:0 },
    { id:2, type:'analyse-situation', text:'A function f is continuous on [a,b] and f(a)<0, f(b)>0. By the Intermediate Value Theorem:', options:['f has a maximum on [a,b]','f has at least one root in (a,b)','f is differentiable on (a,b)','f is monotonically increasing'], correctIndex:1 },
    { id:3, type:'match-following', text:'Match: (P) Eigenvalue (Q) Determinant (R) Trace (S) Rank\nWith: (1) Sum of diagonal elements (2) Scaling factor in Ax=λx (3) Volume scaling factor (4) Dimension of column space', options:['P-2, Q-3, R-1, S-4','P-3, Q-2, R-4, S-1','P-1, Q-4, R-2, S-3','P-4, Q-1, R-3, S-2'], correctIndex:0 },
    { id:4, type:'analyse-situation', text:'A series Σ(1/n) diverges, but Σ(1/n²) converges. Which test distinguishes them most simply?', options:['Ratio test','p-series test','Root test','Alternating series test'], correctIndex:1 },
    { id:5, type:'assertion-reason', text:'Assertion: Every differentiable function is continuous.\nReason: Differentiability at a point requires the function to be defined and limit to exist.', options:['Both true, R explains A','Both true, R does NOT explain A','A true, R false','Both false'], correctIndex:0 },
    { id:6, type:'analyse-situation', text:'A 3×3 matrix has eigenvalues 0, 2, 5. The determinant is:', options:['7','10','0','Cannot determine'], correctIndex:2 },
    { id:7, type:'match-following', text:'Match: (P) Stokes\' Theorem (Q) Green\'s Theorem (R) Divergence Theorem (S) Fundamental Theorem of Calculus\nWith: (1) Line to double integral (2) Surface to volume integral (3) Curve to surface integral (4) Point evaluation', options:['P-3, Q-1, R-2, S-4','P-1, Q-3, R-4, S-2','P-2, Q-4, R-1, S-3','P-4, Q-2, R-3, S-1'], correctIndex:0 },
    { id:8, type:'assertion-reason', text:'Assertion: Every bounded sequence has a convergent subsequence.\nReason: This is the Bolzano-Weierstrass theorem.', options:['Both true, R explains A','Both true, R does NOT explain','A true, R false','Both false'], correctIndex:0 },
    { id:9, type:'analyse-situation', text:'The function f(x)=|x| at x=0 is:', options:['Differentiable and continuous','Continuous but not differentiable','Neither continuous nor differentiable','Differentiable but not continuous'], correctIndex:1 },
    { id:10, type:'analyse-situation', text:'The integral of 1/x from -1 to 1 is:', options:['0 (odd function)','ln(1)-ln(-1)','Divergent (undefined)','2'], correctIndex:2 },
  ],
  'Psychology': [
    { id:1, type:'assertion-reason', text:'Assertion: Classical conditioning involves learning through association.\nReason: Pavlov\'s dog salivated at the sound of a bell after repeated pairing with food.', options:['Both true, R explains A','Both true, R does NOT explain A','A true, R false','Both false'], correctIndex:0 },
    { id:2, type:'analyse-situation', text:'A researcher finds correlation r=0.85 between ice-cream sales and drowning deaths. The best interpretation is:', options:['Ice cream causes drowning','Drowning causes ice-cream sales','A third variable (temperature) likely explains both','The correlation is too low to be significant'], correctIndex:2 },
    { id:3, type:'match-following', text:'Match: (P) Freud (Q) Maslow (R) Skinner (S) Piaget\nWith: (1) Operant conditioning (2) Hierarchy of needs (3) Cognitive development stages (4) Psychoanalysis', options:['P-4, Q-2, R-1, S-3','P-2, Q-4, R-3, S-1','P-1, Q-3, R-4, S-2','P-3, Q-1, R-2, S-4'], correctIndex:0 },
    { id:4, type:'analyse-situation', text:'In an experiment, Group A receives the new drug and Group B receives a sugar pill. Neither patients nor doctors know who gets what. This design is:', options:['Single-blind','Double-blind','Open-label','Crossover'], correctIndex:1 },
    { id:5, type:'assertion-reason', text:'Assertion: Short-term memory has limited capacity.\nReason: Miller\'s magic number suggests we can hold 7±2 chunks of information.', options:['Both true, R explains A','Both true, R does NOT explain','A true, R false','Both false'], correctIndex:0 },
    { id:6, type:'analyse-situation', text:'A child who calls all four-legged animals "doggy" is demonstrating:', options:['Accommodation','Assimilation','Object permanence','Conservation'], correctIndex:1 },
    { id:7, type:'match-following', text:'Match defense mechanism to example:\n(P) Projection (Q) Denial (R) Sublimation (S) Displacement\nWith: (1) Channeling anger into boxing (2) Accusing others of your faults (3) Refusing to accept diagnosis (4) Yelling at family after bad day at work', options:['P-2, Q-3, R-1, S-4','P-3, Q-2, R-4, S-1','P-1, Q-4, R-2, S-3','P-4, Q-1, R-3, S-2'], correctIndex:0 },
    { id:8, type:'assertion-reason', text:'Assertion: The bystander effect reduces helping behavior.\nReason: Diffusion of responsibility increases with group size.', options:['Both true, R explains A','Both true, R does NOT explain A','A true, R false','Both false'], correctIndex:0 },
    { id:9, type:'analyse-situation', text:'A study has p-value = 0.03 with alpha = 0.05. The correct interpretation is:', options:['There is a 3% chance the null hypothesis is true','We reject the null hypothesis','The effect size is large','The study is 97% accurate'], correctIndex:1 },
    { id:10, type:'analyse-situation', text:'A participant remembers words at the beginning and end of a list but forgets middle words. This demonstrates:', options:['Chunking','Serial position effect','Retroactive interference','Proactive interference'], correctIndex:1 },
  ],
  'Computer Science': [
    { id:1, type:'assertion-reason', text:'Assertion: Hash tables provide O(1) average-case lookup.\nReason: Hash functions distribute keys uniformly across buckets.', options:['Both true, R explains A','Both true, R does NOT explain A','A true, R false','Both false'], correctIndex:0 },
    { id:2, type:'analyse-situation', text:'An algorithm has time complexity O(n log n). If input doubles from n to 2n, roughly how does runtime change?', options:['Doubles','Slightly more than doubles','Quadruples','Stays the same'], correctIndex:1 },
    { id:3, type:'match-following', text:'Match: (P) Stack (Q) Queue (R) Heap (S) Hash Table\nWith: (1) FIFO (2) Priority-based extraction (3) LIFO (4) Key-value lookup', options:['P-3, Q-1, R-2, S-4','P-1, Q-3, R-4, S-2','P-2, Q-4, R-1, S-3','P-4, Q-2, R-3, S-1'], correctIndex:0 },
    { id:4, type:'analyse-situation', text:'A recursive function has no base case. What happens?', options:['It returns 0','It runs forever with no output','Stack overflow (runtime error)','Compiler error'], correctIndex:2 },
    { id:5, type:'assertion-reason', text:'Assertion: TCP is more reliable than UDP.\nReason: TCP uses handshaking and acknowledgments to guarantee delivery order.', options:['Both true, R explains A','Both true, R does NOT explain A','A true, R false','Both false'], correctIndex:0 },
    { id:6, type:'analyse-situation', text:'You need to find the shortest path in a weighted graph with negative edge weights But no negative cycles. Which algorithm?', options:['Dijkstra\'s','Bellman-Ford','BFS','Kruskal\'s'], correctIndex:1 },
    { id:7, type:'match-following', text:'Match: (P) Mutex (Q) Semaphore (R) Deadlock (S) Race Condition\nWith: (1) Circular wait (2) Binary lock (3) Counting resource access (4) Non-deterministic bug', options:['P-2, Q-3, R-1, S-4','P-3, Q-2, R-4, S-1','P-1, Q-4, R-2, S-3','P-4, Q-1, R-3, S-2'], correctIndex:0 },
    { id:8, type:'assertion-reason', text:'Assertion: Virtual memory allows programs to use more memory than physically available.\nReason: The OS swaps pages between RAM and disk.', options:['Both true, R explains A','Both true, R does NOT explain A','A true, R false','Both false'], correctIndex:0 },
    { id:9, type:'analyse-situation', text:'Quicksort worst case is O(n²). When does this typically occur?', options:['Random input','Already-sorted input with first element as pivot','Input with all unique elements','Very large input'], correctIndex:1 },
    { id:10, type:'analyse-situation', text:'In a database, you add an index on a frequently queried column. What is the trade-off?', options:['Faster reads, slower writes','Faster writes, slower reads','No trade-off, everything improves','Less storage, faster queries'], correctIndex:0 },
  ],
};

// Default/generic questions for fields not in the bank
const defaultQuestions: Question[] = [
  { id:1, type:'assertion-reason', text:'Assertion: Peer review improves research quality.\nReason: External experts can identify methodological flaws the author may miss.', options:['Both true, R explains A','Both true, R does NOT explain A','A true, R false','Both false'], correctIndex:0 },
  { id:2, type:'analyse-situation', text:'A researcher observes a strong pattern in a small sample (n=5). Before publishing conclusions, they should:', options:['Publish immediately as the pattern is clear','Replicate with larger sample size','Change the hypothesis to match results','Discard the data and start over'], correctIndex:1 },
  { id:3, type:'match-following', text:'Match research method to strength:\n(P) Experiment (Q) Survey (R) Case Study (S) Meta-Analysis\nWith: (1) Establishing causation (2) Large sample feasibility (3) In-depth individual analysis (4) Combining multiple studies', options:['P-1, Q-2, R-3, S-4','P-2, Q-1, R-4, S-3','P-3, Q-4, R-1, S-2','P-4, Q-3, R-2, S-1'], correctIndex:0 },
  { id:4, type:'analyse-situation', text:'Your experimental results contradict your hypothesis. The scientifically correct response is:', options:['Adjust data to fit hypothesis','Reject the hypothesis and investigate further','Ignore the results','Repeat until desired results appear'], correctIndex:1 },
  { id:5, type:'assertion-reason', text:'Assertion: Correlation does not imply causation.\nReason: Two variables may be correlated due to a confounding third variable.', options:['Both true, R explains A','Both true, R does NOT explain A','A true, R false','Both false'], correctIndex:0 },
  { id:6, type:'analyse-situation', text:'Type I error vs Type II error: rejecting a true null hypothesis is:', options:['Type I error','Type II error','Both','Neither'], correctIndex:0 },
  { id:7, type:'match-following', text:'Match: (P) Mean (Q) Median (R) Mode (S) Standard Deviation\nWith: (1) Most frequent value (2) Average value (3) Middle value (4) Spread measure', options:['P-2, Q-3, R-1, S-4','P-1, Q-2, R-4, S-3','P-3, Q-1, R-2, S-4','P-4, Q-2, R-3, S-1'], correctIndex:0 },
  { id:8, type:'assertion-reason', text:'Assertion: Large datasets reduce the impact of outliers on statistical measures.\nReason: With more data points each individual value contributes less to the overall statistic.', options:['Both true, R explains A','Both true, R does NOT explain A','A true, R false','Both false'], correctIndex:0 },
  { id:9, type:'analyse-situation', text:'You need to choose between accuracy and interpretability for a critical medical diagnosis system. You should prioritize:', options:['Maximum accuracy regardless of interpretability','Balance of both with emphasis on interpretability for accountability','Only interpretability, accuracy is irrelevant','Use the simplest model available'], correctIndex:1 },
  { id:10, type:'analyse-situation', text:'A model predicts outcomes perfectly on historical data but fails on new data. This is likely:', options:['Underfitting','Overfitting','Random chance','Perfect generalization'], correctIndex:1 },
];

export function generateQuestions(field: string): Question[] {
  const questions = questionBank[field] || defaultQuestions;
  // Shuffle the questions
  const shuffled = [...questions].sort(() => Math.random() - 0.5);
  return shuffled.slice(0, 10).map((q, i) => ({ ...q, id: i + 1 }));
}
